apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: subnet-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.100.150-192.168.100.152

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: subnet-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - subnet-pool
