apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-system
  namespace: metallb-system
spec:
  addresses:
  - 172.28.0.135-172.28.0.142

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-system
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-system
