apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-demo
data:
  virtual_host: "vhost1.localhost.com"
  index.html: | 
     <html>
       <h1> Teste </h1>
     </html>
   vhost.confg:  |
      server {
        listen 80;
        listen [::]:80;

        root /usr/share/nginx/app1
      } 