apiVersion: v1
kind: Secret
metadata:
  name: credencial
type: kubernetes.io/basic-auth
data:
  username: d2lsaWFt
  password: d2lsaWFt

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: credencial
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: credencial
                key: password
        volumeMounts:
          - name: credencial 
            mountPath: "/tmp"
            readOnly: true
      volumes:
         - name: credencial 
           secret:
              secretName: credencial

