apiVersion: v1
kind: Secret
metadata:
  name: credencial
type: kubernetes.io/basic-auth
data:
  username: bWF0ZXVzCg==
  password: bWF0ZXVzCg==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: credencial
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: credencial
                key: password

