apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo-multi
  name: demo-multi
spec:
  containers:
  - image: httpd
    name: demo
  - image: alpine
    name: debug
    command:
      - sh
      - -c
      - sleep 99999999