apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo
  name: demo
spec:
  containers:
  - image: httpd
    name: demo
  initContainers:
  - image: busybox:1.28
    name: waitfordns
    command:
      - sh
      - -c
      - until nslookup order-database; do echo "Trying to resolve order-database"; sleep 2; done
